/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManagerWorkArea;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Project.Project;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Karishma
 */
public class ProjectsJPanel extends javax.swing.JPanel {
    /**
     * Creates new form Projects
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;

    public ProjectsJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        populateProjectTable();
    }

    public void populateProjectTable() {
        DefaultTableModel model = (DefaultTableModel) tblViewProjects.getModel();

        model.setRowCount(0);
        for (Project project : enterprise.getProjectDirectory().getProjectList()) {
            Object[] row = new Object[2];
            //row[0] = project.getId();
            row[0] = project;
            row[1] = project.getBudget();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDelete = new javax.swing.JButton();
        lblProjectName = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblBudget = new javax.swing.JLabel();
        txtProjectBudget = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewProjects = new javax.swing.JTable();
        lblWarning = new javax.swing.JLabel();
        lblHeader = new javax.swing.JLabel();
        cbName = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(700, 700));
        setMinimumSize(new java.awt.Dimension(700, 700));
        setPreferredSize(new java.awt.Dimension(700, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDelete.setBackground(new java.awt.Color(113, 160, 160));
        btnDelete.setText("Delete Project");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, -1, -1));

        lblProjectName.setText("Project Name:");
        add(lblProjectName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, -1, -1));

        btnAdd.setBackground(new java.awt.Color(113, 160, 160));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 590, 123, -1));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back-button.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 40, 40));

        lblBudget.setText("Budget:");
        add(lblBudget, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, -1, -1));
        add(txtProjectBudget, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, 180, -1));

        tblViewProjects.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Budget"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblViewProjects);
        if (tblViewProjects.getColumnModel().getColumnCount() > 0) {
            tblViewProjects.getColumnModel().getColumn(0).setResizable(false);
            tblViewProjects.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 110, 470, 240));

        lblWarning.setForeground(new java.awt.Color(255, 0, 51));
        lblWarning.setText("* Budget currency is considered to be in US Dollar");
        add(lblWarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 650, -1, -1));

        lblHeader.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Projects");
        add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 220, 26));

        cbName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Provide Medication", "Provide Treatment", "Donate Basic Amenities"}));
        cbName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNameActionPerformed(evt);
            }
        });
        add(cbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 180, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String projectName = cbName.getSelectedItem().toString();
        String budgetText = txtProjectBudget.getText();
        if (budgetText != "" || projectName != "") {
            
            String regex = "^[a-z A-Z]+$";
            Pattern namePattern = Pattern.compile(regex);
            Matcher nameMatcher = namePattern.matcher(projectName);

            if(!nameMatcher.matches()){
                 JOptionPane.showMessageDialog(null, "Invalid characters in project name", "Warning", JOptionPane.WARNING_MESSAGE);
                 return;
            }
            
            regex = "^[0-9]+$";
            Pattern intPattern = Pattern.compile(regex);
            Matcher intMatcher = intPattern.matcher(budgetText);

            if(!intMatcher.matches()){
                 JOptionPane.showMessageDialog(null, "Invalid characters in budget, enter only numbers", "Warning", JOptionPane.WARNING_MESSAGE);
                 return;
            }
            
            int budget = Integer.parseInt(budgetText);
            System.out.println(enterprise.getAccountDirectory().getBalance());            
            if(budget <= enterprise.getAccountDirectory().getBalance()){
                Project project = new Project();
                project = enterprise.getProjectDirectory().addProject(project);
                project.setName(projectName);
                project.setBudget(budget);
                project.setManager(userAccount.getEmployee());

                //deducting the budget from balance
                int balance = enterprise.getAccountDirectory().getBalance() - budget;
                enterprise.getAccountDirectory().setBalance(balance);

                JOptionPane.showMessageDialog(null, "Project added successfully", "Information", JOptionPane.INFORMATION_MESSAGE);
                txtProjectBudget.setText("");
                populateProjectTable();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "No enough budget for the Project", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please enter both the fields", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblViewProjects.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Project project = (Project) tblViewProjects.getValueAt(selectedRow, 1);
//        for(Project p : enterprise.getProjectDirectory().getProjectList()){
//            if(project.equals(p)){
        enterprise.getProjectDirectory().RemoveProject(project);
        JOptionPane.showMessageDialog(null, "Project deleted successfully", "Information", JOptionPane.INFORMATION_MESSAGE);

        populateProjectTable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void cbNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JComboBox<String> cbName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBudget;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblProjectName;
    private javax.swing.JLabel lblWarning;
    private javax.swing.JTable tblViewProjects;
    private javax.swing.JTextField txtProjectBudget;
    // End of variables declaration//GEN-END:variables
}
