/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ApplicantWorkArea;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import UserInterface.GuestWorkArea.ApplyForJobJPanel;
import UserInterface.GuestWorkArea.RaiseIssueJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author shalini
 */
public class ApplicantWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount userAccount;
    private DB4OUtil dB4OUtil;

    public ApplicantWorkAreaJPanel(JPanel userProcessContainer, EcoSystem system, UserAccount userAccount, DB4OUtil dB4OUtil) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.userAccount = userAccount;
        this.dB4OUtil = dB4OUtil;
        populateForm();
    }

    public void populateForm() {
        lblName.setText(userAccount.getApplicant().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        lblHi = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        btnViewJobs = new javax.swing.JButton();
        btnRaiseIssue = new javax.swing.JButton();
        btnViewApplications = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeader.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Applicant Work Area");
        add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 19, 670, 26));

        lblHi.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblHi.setText("Hi,");
        add(lblHi, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 77, 22, 30));

        lblName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblName.setText("Appl");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 150, 22));

        btnViewJobs.setBackground(new java.awt.Color(113, 160, 160));
        btnViewJobs.setText("View Jobs");
        btnViewJobs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewJobsActionPerformed(evt);
            }
        });
        add(btnViewJobs, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 125, 217, -1));

        btnRaiseIssue.setBackground(new java.awt.Color(113, 160, 160));
        btnRaiseIssue.setText("Raise A Request");
        btnRaiseIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaiseIssueActionPerformed(evt);
            }
        });
        add(btnRaiseIssue, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 224, 217, -1));

        btnViewApplications.setBackground(new java.awt.Color(113, 160, 160));
        btnViewApplications.setText("View Application Status");
        btnViewApplications.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewApplicationsActionPerformed(evt);
            }
        });
        add(btnViewApplications, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 175, 217, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/people.gif"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 730, 360));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewJobsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewJobsActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        ApplyForJobJPanel afjp = new ApplyForJobJPanel(userProcessContainer, system, dB4OUtil, userAccount, "A");
        userProcessContainer.add("afjp", afjp);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewJobsActionPerformed

    private void btnRaiseIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaiseIssueActionPerformed
//        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        RaiseIssueJPanel rijp = new RaiseIssueJPanel(userProcessContainer, userAccount, system);
        userProcessContainer.add("rijp", rijp);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnRaiseIssueActionPerformed

    private void btnViewApplicationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewApplicationsActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        ApplicationStatusJPanel asjp = new ApplicationStatusJPanel(userProcessContainer, system, userAccount);
        userProcessContainer.add("asjp", asjp);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewApplicationsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRaiseIssue;
    private javax.swing.JButton btnViewApplications;
    private javax.swing.JButton btnViewJobs;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblHi;
    private javax.swing.JLabel lblName;
    // End of variables declaration//GEN-END:variables
}
