/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CareTakerWorkArea;

import UserInterface.CoordinatorWorkArea.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
/**
 *
 * @author Vardhana Bhatt
 */
public class CareTakerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CareTakerWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;

    public CareTakerWorkAreaJPanel(JPanel userProcessContainer, EcoSystem system, UserAccount userAccount, Organization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        btnManageSenior = new javax.swing.JButton();
        btnViewSenior = new javax.swing.JButton();
        btnSendForTreatment = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeader.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("CareTaker Work Area");
        add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 270, 26));

        btnManageSenior.setBackground(new java.awt.Color(113, 160, 160));
        btnManageSenior.setText("Manage Senior Care");
        btnManageSenior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageSeniorActionPerformed(evt);
            }
        });
        add(btnManageSenior, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 200, 40));

        btnViewSenior.setBackground(new java.awt.Color(113, 160, 160));
        btnViewSenior.setText("View Seniors");
        btnViewSenior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSeniorActionPerformed(evt);
            }
        });
        add(btnViewSenior, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 200, 40));

        btnSendForTreatment.setBackground(new java.awt.Color(113, 160, 160));
        btnSendForTreatment.setText("Send Senior for Treatment");
        btnSendForTreatment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendForTreatmentActionPerformed(evt);
            }
        });
        add(btnSendForTreatment, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 200, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/caretaker.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 550, 410));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageSeniorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageSeniorActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        ManageSeniorCareJPanel opjp = new ManageSeniorCareJPanel(userProcessContainer, system, userAccount, organization, enterprise);
        userProcessContainer.add("OngoingProjectsJPanel", opjp);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageSeniorActionPerformed

    private void btnViewSeniorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSeniorActionPerformed
        // TODO add your handling code here:

        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        ViewSeniorCareJPanel abcd = new ViewSeniorCareJPanel(userProcessContainer, system, userAccount, organization, enterprise);
        userProcessContainer.add("abcd", abcd);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewSeniorActionPerformed

    private void btnSendForTreatmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendForTreatmentActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        SendSeniorForTreatmentJPanel efgh = new SendSeniorForTreatmentJPanel(userProcessContainer, system, userAccount, organization, enterprise);
        userProcessContainer.add("efgh", efgh);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnSendForTreatmentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageSenior;
    private javax.swing.JButton btnSendForTreatment;
    private javax.swing.JButton btnViewSenior;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblHeader;
    // End of variables declaration//GEN-END:variables
}
